import random
from locust import HttpUser, task

book_list = [
    {"title": "Jane Eyre", "author": "Jane Austen", "category": "period drama"},
    {"title": "Great Expectations", "author": "Charles Dickens", "category": "period drama"},
    {"title": "Bourne Identity", "author": "Robert Ludlum", "category": "mystery/thriller"},
    {"title": "Da Vinci Code", "author": "Dan Brown", "category": "mystery/thriller"},
    {"title": "The Match Girl", "author": "Charles Dickens", "category": "tragedy"},
    {"title": "Pride and Prejudice", "author": "Jane Austen", "category": "romance"},
    {"title": "Moby Dick", "author": "Herman Melville", "category": "adventure"},
    {"title": "War and Peace", "author": "Leo Tolstoy", "category": "historical fiction"},
    {"title": "1984", "author": "George Orwell", "category": "dystopian"},
    {"title": "To Kill a Mockingbird", "author": "Harper Lee", "category": "classic"},
    {"title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "category": "classic"},
    {"title": "The Catcher in the Rye", "author": "J.D. Salinger", "category": "classic"},
    {"title": "Little Women", "author": "Louisa May Alcott", "category": "classic"},
    {"title": "The Hobbit", "author": "J.R.R. Tolkien", "category": "fantasy"},
    {"title": "The Lord of the Rings", "author": "J.R.R. Tolkien", "category": "fantasy"},
    {"title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Chamber of Secrets", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Prisoner of Azkaban", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Goblet of Fire", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Order of the Phoenix", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Half-Blood Prince", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Deathly Hallows", "author": "J.K. Rowling", "category": "fantasy"},
    {"title": "The Chronicles of Narnia", "author": "C.S. Lewis", "category": "fantasy"},
    {"title": "A Tale of Two Cities", "author": "Charles Dickens", "category": "historical fiction"},
    {"title": "Crime and Punishment", "author": "Fyodor Dostoevsky", "category": "classic"},
    {"title": "The Brothers Karamazov", "author": "Fyodor Dostoevsky", "category": "classic"},
    {"title": "Anna Karenina", "author": "Leo Tolstoy", "category": "classic"},
    {"title": "Les Misérables", "author": "Victor Hugo", "category": "classic"},
    {"title": "The Count of Monte Cristo", "author": "Alexandre Dumas", "category": "adventure"},
    {"title": "The Three Musketeers", "author": "Alexandre Dumas", "category": "adventure"},
    {"title": "Don Quixote", "author": "Miguel de Cervantes", "category": "classic"},
    {"title": "Ulysses", "author": "James Joyce", "category": "modernist"},
    {"title": "The Odyssey", "author": "Homer", "category": "epic"},
    {"title": "The Iliad", "author": "Homer", "category": "epic"},
    {"title": "The Divine Comedy", "author": "Dante Alighieri", "category": "epic"},
    {"title": "Paradise Lost", "author": "John Milton", "category": "epic"},
    {"title": "The Canterbury Tales", "author": "Geoffrey Chaucer", "category": "classic"},
    {"title": "The Picture of Dorian Gray", "author": "Oscar Wilde", "category": "classic"},
    {"title": "Dracula", "author": "Bram Stoker", "category": "horror"},
    {"title": "Frankenstein", "author": "Mary Shelley", "category": "horror"},
    {"title": "Brave New World", "author": "Aldous Huxley", "category": "dystopian"},
    {"title": "Fahrenheit 451", "author": "Ray Bradbury", "category": "dystopian"},
    {"title": "The Road", "author": "Cormac McCarthy", "category": "dystopian"},
    {"title": "The Handmaid's Tale", "author": "Margaret Atwood", "category": "dystopian"},
    {"title": "Animal Farm", "author": "George Orwell", "category": "satire"},
    {"title": "Catch-22", "author": "Joseph Heller", "category": "satire"},
    {"title": "Slaughterhouse-Five", "author": "Kurt Vonnegut", "category": "satire"},
    {"title": "One Hundred Years of Solitude", "author": "Gabriel Garcia Marquez", "category": "magic realism"},
    {"title": "Love in the Time of Cholera", "author": "Gabriel Garcia Marquez", "category": "magic realism"},
    {"title": "Beloved", "author": "Toni Morrison", "category": "historical fiction"},
    {"title": "Song of Solomon", "author": "Toni Morrison", "category": "historical fiction"},
    {"title": "Gone with the Wind", "author": "Margaret Mitchell", "category": "historical fiction"},
    {"title": "The Grapes of Wrath", "author": "John Steinbeck", "category": "historical fiction"},
    {"title": "East of Eden", "author": "John Steinbeck", "category": "historical fiction"},
    {"title": "Of Mice and Men", "author": "John Steinbeck", "category": "classic"},
    {"title": "The Old Man and the Sea", "author": "Ernest Hemingway", "category": "classic"},
    {"title": "For Whom the Bell Tolls", "author": "Ernest Hemingway", "category": "historical fiction"},
    {"title": "The Sun Also Rises", "author": "Ernest Hemingway", "category": "classic"},
    {"title": "A Farewell to Arms", "author": "Ernest Hemingway", "category": "historical fiction"},
    {"title": "The Bell Jar", "author": "Sylvia Plath", "category": "classic"},
    {"title": "On the Road", "author": "Jack Kerouac", "category": "classic"},
    {"title": "The Stranger", "author": "Albert Camus", "category": "existential"},
    {"title": "The Plague", "author": "Albert Camus", "category": "existential"},
    {"title": "Invisible Man", "author": "Ralph Ellison", "category": "classic"},
    {"title": "Native Son", "author": "Richard Wright", "category": "classic"},
    {"title": "Their Eyes Were Watching God", "author": "Zora Neale Hurston", "category": "classic"},
    {"title": "Things Fall Apart", "author": "Chinua Achebe", "category": "classic"},
    {"title": "Heart of Darkness", "author": "Joseph Conrad", "category": "classic"},
    {"title": "Lord of the Flies", "author": "William Golding", "category": "classic"},
    {"title": "The Alchemist", "author": "Paulo Coelho", "category": "philosophical"},
    {"title": "Siddhartha", "author": "Hermann Hesse", "category": "philosophical"},
    {"title": "The Little Prince", "author": "Antoine de Saint-Exupéry", "category": "children's"},
    {"title": "The Wind in the Willows", "author": "Kenneth Grahame", "category": "children's"},
    {"title": "Alice's Adventures in Wonderland", "author": "Lewis Carroll", "category": "children's"},
    {"title": "Through the Looking-Glass", "author": "Lewis Carroll", "category": "children's"},
    {"title": "Peter Pan", "author": "J.M. Barrie", "category": "children's"},
    {"title": "Charlotte's Web", "author": "E.B. White", "category": "children's"},
    {"title": "The Secret Garden", "author": "Frances Hodgson Burnett", "category": "children's"},
]

book_list_update = [
    {"title": "Jane Eyre", "author": "Update_Jane Austen", "category": "period drama"},
    {"title": "Great Expectations", "author": "Update_Charles Dickens", "category": "period drama"},
    {"title": "Bourne Identity", "author": "Update_Robert Ludlum", "category": "mystery/thriller"},
    {"title": "Da Vinci Code", "author": "Update_Dan Brown", "category": "mystery/thriller"},
    {"title": "The Match Girl", "author": "Update_Charles Dickens", "category": "tragedy"},
    {"title": "Pride and Prejudice", "author": "Update_Jane Austen", "category": "romance"},
    {"title": "Moby Dick", "author": "Update_Herman Melville", "category": "adventure"},
    {"title": "War and Peace", "author": "Update_Leo Tolstoy", "category": "historical fiction"},
    {"title": "1984", "author": "Update_George Orwell", "category": "dystopian"},
    {"title": "To Kill a Mockingbird", "author": "Update_Harper Lee", "category": "classic"},
    {"title": "The Great Gatsby", "author": "Update_F. Scott Fitzgerald", "category": "classic"},
    {"title": "The Catcher in the Rye", "author": "Update_J.D. Salinger", "category": "classic"},
    {"title": "Little Women", "author": "Update_Louisa May Alcott", "category": "classic"},
    {"title": "The Hobbit", "author": "Update_J.R.R. Tolkien", "category": "fantasy"},
    {"title": "The Lord of the Rings", "author": "Update_J.R.R. Tolkien", "category": "fantasy"},
    {"title": "Harry Potter and the Sorcerer's Stone", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Chamber of Secrets", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Prisoner of Azkaban", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Goblet of Fire", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Order of the Phoenix", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Half-Blood Prince", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "Harry Potter and the Deathly Hallows", "author": "Update_J.K. Rowling", "category": "fantasy"},
    {"title": "The Chronicles of Narnia", "author": "Update_C.S. Lewis", "category": "fantasy"},
    {"title": "A Tale of Two Cities", "author": "Update_Charles Dickens", "category": "historical fiction"},
    {"title": "Crime and Punishment", "author": "Update_Fyodor Dostoevsky", "category": "classic"},
    {"title": "The Brothers Karamazov", "author": "Update_Fyodor Dostoevsky", "category": "classic"},
    {"title": "Anna Karenina", "author": "Update_Leo Tolstoy", "category": "classic"},
    {"title": "Les Misérables", "author": "Update_Victor Hugo", "category": "classic"},
    {"title": "The Count of Monte Cristo", "author": "Update_Alexandre Dumas", "category": "adventure"},
    {"title": "The Three Musketeers", "author": "Update_Alexandre Dumas", "category": "adventure"},
    {"title": "Don Quixote", "author": "Update_Miguel de Cervantes", "category": "classic"},
    {"title": "Ulysses", "author": "Update_James Joyce", "category": "modernist"},
    {"title": "The Odyssey", "author": "Update_Homer", "category": "epic"},
    {"title": "The Iliad", "author": "Update_Homer", "category": "epic"},
    {"title": "The Divine Comedy", "author": "Update_Dante Alighieri", "category": "epic"},
    {"title": "Paradise Lost", "author": "Update_John Milton", "category": "epic"},
    {"title": "The Canterbury Tales", "author": "Update_Geoffrey Chaucer", "category": "classic"},
    {"title": "The Picture of Dorian Gray", "author": "Update_Oscar Wilde", "category": "classic"},
    {"title": "Dracula", "author": "Update_Bram Stoker", "category": "horror"},
    {"title": "Frankenstein", "author": "Update_Mary Shelley", "category": "horror"},
    {"title": "Brave New World", "author": "Update_Aldous Huxley", "category": "dystopian"},
    {"title": "Fahrenheit 451", "author": "Update_Ray Bradbury", "category": "dystopian"},
    {"title": "The Road", "author": "Update_Cormac McCarthy", "category": "dystopian"},
    {"title": "The Handmaid's Tale", "author": "Update_Margaret Atwood", "category": "dystopian"},
    {"title": "Animal Farm", "author": "Update_George Orwell", "category": "satire"},
    {"title": "Catch-22", "author": "Update_Joseph Heller", "category": "satire"},
    {"title": "Slaughterhouse-Five", "author": "Update_Kurt Vonnegut", "category": "satire"},
    {"title": "One Hundred Years of Solitude", "author": "Update_Gabriel Garcia Marquez", "category": "magic realism"},
    {"title": "Love in the Time of Cholera", "author": "Update_Gabriel Garcia Marquez", "category": "magic realism"},
    {"title": "Beloved", "author": "Update_Toni Morrison", "category": "historical fiction"},
    {"title": "Song of Solomon", "author": "Update_Toni Morrison", "category": "historical fiction"},
    {"title": "Gone with the Wind", "author": "Update_Margaret Mitchell", "category": "historical fiction"},
    {"title": "The Grapes of Wrath", "author": "Update_John Steinbeck", "category": "historical fiction"},
    {"title": "East of Eden", "author": "Update_John Steinbeck", "category": "historical fiction"},
    {"title": "Of Mice and Men", "author": "Update_John Steinbeck", "category": "classic"},
    {"title": "The Old Man and the Sea", "author": "Update_Ernest Hemingway", "category": "classic"},
    {"title": "For Whom the Bell Tolls", "author": "Update_Ernest Hemingway", "category": "historical fiction"},
    {"title": "The Sun Also Rises", "author": "Update_Ernest Hemingway", "category": "classic"},
    {"title": "A Farewell to Arms", "author": "Update_Ernest Hemingway", "category": "historical fiction"},
    {"title": "The Bell Jar", "author": "Update_Sylvia Plath", "category": "classic"},
    {"title": "On the Road", "author": "Update_Jack Kerouac", "category": "classic"},
    {"title": "The Stranger", "author": "Update_Albert Camus", "category": "existential"},
    {"title": "The Plague", "author": "Update_Albert Camus", "category": "existential"},
    {"title": "Invisible Man", "author": "Update_Ralph Ellison", "category": "classic"},
    {"title": "Native Son", "author": "Update_Richard Wright", "category": "classic"},
    {"title": "Their Eyes Were Watching God", "author": "Update_Zora Neale Hurston", "category": "classic"},
    {"title": "Things Fall Apart", "author": "Update_Chinua Achebe", "category": "classic"},
    {"title": "Heart of Darkness", "author": "Update_Joseph Conrad", "category": "classic"},
    {"title": "Lord of the Flies", "author": "Update_William Golding", "category": "classic"},
    {"title": "The Alchemist", "author": "Update_Paulo Coelho", "category": "philosophical"},
    {"title": "Siddhartha", "author": "Update_Hermann Hesse", "category": "philosophical"},
    {"title": "The Little Prince", "author": "Update_Antoine de Saint-Exupéry", "category": "children's"},
    {"title": "The Wind in the Willows", "author": "Update_Kenneth Grahame", "category": "children's"},
    {"title": "Alice's Adventures in Wonderland", "author": "Update_Lewis Carroll", "category": "children's"},
    {"title": "Through the Looking-Glass", "author": "Update_Lewis Carroll", "category": "children's"},
    {"title": "Peter Pan", "author": "Update_J.M. Barrie", "category": "children's"},
    {"title": "Charlotte's Web", "author": "Update_E.B. White", "category": "children's"},
    {"title": "The Secret Garden", "author": "Update_Frances Hodgson Burnett", "category": "children's"},
]

class HelloWorldUser(HttpUser):
    @task # CREATE
    def books_create(self):
        with self.client.post("/books/create_book", json=random.choice(book_list), catch_response=True) as response:
            if (response.status_code != 200) and (response.status_code != 201):
                response.failure("message is {}".format(response.json()))

    @task # READ
    def books_query(self):
        with self.client.get("/books", catch_response=True) as response:
            if (response.status_code != 200) and (response.status_code != 201):
                response.failure("message is {}".format(response.json()))
        

    @task # UPDATE
    def books_update(self):
        with self.client.put("/books/update_book", json=random.choice(book_list_update), catch_response=True) as response:
            if (response.status_code != 200) and (response.status_code != 201):
                response.failure("message is {}".format(response.json()))

    @task # DELETE
    def books_delete(self):
        with self.client.delete("/books/delete_book?book_title={}".format(random.choice(book_list)["title"]), catch_response=True) as response:
            if (response.status_code != 200) and (response.status_code != 201):
                response.failure("message is {}".format(response.json()))